### PR TITLE
Securing TFE access part 2

### PR DESCRIPTION
**Pull request by MDL-Cloud-Ops**
Part of https://github.mdl.cloud/DevOps/devops.github.mdl.cloud/issues/1015.

Adds the new ELBs to DNS, enables SSH direct to the instances via private IP address and registers TFE with the new ELBs.

Release checklist:

* [ ] Manually adjust security groups on the existing instance
* [ ] Manually change membership of the ELBs
* [ ] Plan and apply with no change to instance or ELBs

Future changes will remove the original access and perform additional clean up.

### CODE REVIEW

**Comment by lbrucher** [comment]
Again, probably not the best person to review but seems ok.

**Comment by MDL-Cloud-Ops** [comment]
These are low impact changes and I am expecting you to ramp up @lbrucher :)

**Comment by MDL-Cloud-Ops** [comment]
Change to launch configuration forced a cycle of TFE.

**Comment by stevehorsfield** [comment]
MDL Cloud Ops actions here are by me!

**Pull request merged**
